repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements

  - repo: local
    hooks:
      - id: types
        name: types
        entry: uv run nox -s types --
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: security
        name: security
        entry: uv run bandit -r src
        language: system
        types: [python]
        require_serial: true
